### ISSUE TITLE
Loading additional comments doesn't work (on root level)

### ISSUE THREAD

**Issue by patte** [orbiting/republik-frontend#149]
## Bug Report

If I am on a discussion page and somebody else writes a new top level comment, the page correctly shows "Ein weiterer Kommentar" on the bottom of the page. But when I click on it nothing happens. If I reload the page, the comment appears.

**Steps to Reproduce**

- go to a discussion page and scroll to the very bottom
- make someone else post a new toplevel comment.
- wait for "Ein weiterer Kommentar" to appear and click on it.

**Actual Results**

- nothing happens

**Expected Results**

- the comment should appear and replace "Ein weiterer Kommentar"

**Environment**

- Ubuntu 18.10 - Chromium Version 67.0.3396.99
- iOS 11.4 - Safari

**Comment by tpreusse** [comment]
Similar case:
> ständig wird mir angezeigt "ein weiterer Beitrag", dabei gibt es keine weiteren Diskussionsbeiträge im Forum. Auch wenn ich geantwortet habe auf einen Beitrag steht unten "Ein weiterer Beitrag", ich klicke an und nix ists..:)
![bitte_mehr](https://user-images.githubusercontent.com/410211/51180818-ca1e7e80-18c9-11e9-8f59-804eb8e9b5da.png)

**Comment by tpreusse** [comment]
Should be fixed since https://github.com/orbiting/republik-frontend/pull/309
