### ISSUE TITLE
discussion preferences header hidden on small devices

### ISSUE THREAD

**Issue by patte** [orbiting/republik-frontend#239]
## Bug Report

The header of the discussion preferences is hidden under the main header on small screens. This makes it impossible to close and therefore edit/save the preferences.

Bug report in “Allgemeines Feedback”
https://www.republik.ch/dialog?t=general&id=ec6ba678-8eb2-45e0-97fa-20d3a4d58b64&focus=6170b613-f15a-48f7-86d9-fd571418f6f0
![6bfe0934-deb3-46e6-8300-48b51779876f](https://user-images.githubusercontent.com/3500621/50383219-7bf1d300-06af-11e9-91da-32069331d9f1.jpeg)

**Steps to Reproduce**

- click the “pen-icon” in the comment composer on a mobile device.

**Actual Results**
app:
![b99f428d-f2f5-41e0-a800-588717bd2580](https://user-images.githubusercontent.com/3500621/50383230-ae9bcb80-06af-11e9-9adf-7a4ec69eb7c4.jpeg)
safari:
![7eb4db55-c962-479d-b708-5b504070c373](https://user-images.githubusercontent.com/3500621/50383231-ae9bcb80-06af-11e9-8a1a-ba5c3fb7291e.jpeg)

**Environment**

- Republik App 1.0.1 / Safari iOS 12.0.1
- Android (see first screenshot)

**Possible Solutions**

I don’t even see a workaround right now.

**Comment by tpreusse** [comment]
fixed with https://github.com/orbiting/republik-frontend/commit/e40074662a0495d4258f599bf6d04fae48b984e7
