### ISSUE TITLE
Enhancement: Login via E-Mailadresse

### ISSUE THREAD

**Issue by lwihler** [orbiting/republik-frontend#252]
## Enhancement

Um VerlegerInnen das Anmelden zu erleichtern,  wäre es hilfreich, einen Link zu verschicken, der die Mailadresse bereits eingetragen hat. 

**Steps to Introduce**

Auf https://www.republik.ch/anmelden gibt man die eigene Mailadresse an und klickt dann auf "Anmelden"
Mit dem neuen Enhancement könnte das aufwändige Mailadresse eintippen übersprungen werden und man müsste nur noch auf "Anmelden" klicken. (Ähnliches Vorgehen wie bei Gutscheincode)

Vorschlag: 
https://www.republik.ch/anmelden?mail=liliane.wihler@republik.ch

**Expected Results**

![image](https://user-images.githubusercontent.com/38752973/52208587-71675380-2881-11e9-835d-a7fc000ec30f.png)

**Comment by tpreusse** [comment]
Bei Konto geht das bereits:
https://www.republik.ch/konto?email=liliane.wihler@republik.ch

Füge es nachher noch beim sign in hinzu.

**Comment by tpreusse** [comment]
geht mit dem nächsten deploy raus
