### ISSUE TITLE
After submitting a comment, "Ein weiterer Beitrag" appears.

### ISSUE THREAD

**Issue by uxengine** [orbiting/republik-frontend#262]
## Bug Report

Related to https://github.com/orbiting/republik-frontend/issues/149, but technically not necessarily the same issue:
If you write a root comment yourself, an unwanted "Ein weiterer Beitrag" appears. On click it disappears.

**Steps to Reproduce**

Write a root comment and observe the end of the comments section.

**Actual Results**
"Ein weiterer Beitrag" appears.
<img width="725" alt="screenshot 2019-02-21 at 11 25 41" src="https://user-images.githubusercontent.com/23520051/53162717-eb5f4280-35cc-11e9-9aa4-e87ca57124f9.png">

**Expected Results**

"Ein weiterer Beitrag" should **not** appear.

**Environment**

- OS: Mac
- Browser: Chrome

**Possible Solutions**
The discussion page subscribes to created comments. If you submit a comment yourself, the subscription also fires. Keeping track of comment IDs you created yourself could solve this particular issue (I have a working prototype).

**Comment by tpreusse** [comment]
Solved with https://github.com/orbiting/republik-frontend/pull/265
