### ISSUE TITLE
Enhancement: Save draft comment

### ISSUE THREAD

**Issue by patrickvenetz** [orbiting/republik-frontend#268]
## Enhancement

Enable interface to keep last drafted comments until submitted which would greatly extend experience for our most verbose and meticulous users.

As a user I would fine it horribly handy to have frontend keeping my drafted comments once I start typing and restored drafted comments when I navigate away and return at a later point in time.

Might be stored locally (👍) or, for sync purposes, via API (👎).

Related to https://github.com/orbiting/app/issues/183

**Comment by tpreusse** [comment]
Local storage implemented in https://github.com/orbiting/republik-frontend/pull/309
