### ISSUE TITLE
"Abo teilen" button redirects to marketing page after email confirmed.

### ISSUE THREAD

**Issue by eightam** [orbiting/republik-frontend#272]
## Bug Report

If an "Abo teilen" is accepted and the confirmation link is opened in the same browser a page with a big green button "Magazin lesen" appears. If the button is clicked, the page jumps to the marketing front. If the browser is refreshed, the user is logged in and on the magazine front.

**Steps to Reproduce**

Get an Abo shared to you, accept the invitation, log in in the same browser, click the button.

**Actual Results**

If an "Abo teilen" is accepted and the confirmation link is opened in the same browser a page with a big green button "Magazin lesen" appears. If the button is clicked, the page jumps to the marketing front. If the browser is refreshed, the user is logged in and on the magazine front.

**Expected Results**

The "Magazin lesen" button should jump to the magazine front.

**Environment**

Tested on Desktop Browsers
- OS: OSX 10.14.3 and Ubuntu
- Browser: Chrome 71, Firefox 65.01

**Possible Solutions**

The "Magazin lesen" button should do a hard refresh and jump to the magazine front.

**Comment by patrickvenetz** [comment]
Unable to reproduce in staging environment. «Magazin lesen» does not appear after sign in completed.

Can be reproduced in production environment.
