### ISSUE TITLE
Missing Markdown node prints overly aggressive error message

### ISSUE THREAD

**Issue by patrickvenetz** [orbiting/republik-frontend#273]
## Bug Report

Components using MDAST/Markdown may throw a prominent "Missing Markdown node type" error.

<img width="679" alt="screen shot 2019-03-05 at 06 40 43" src="https://user-images.githubusercontent.com/331800/53807934-3aa05e00-3f51-11e9-87fa-b7cfdda28026.png">

Screenshot derived from an article with a boldened phrase and a term in it that was additionally marked as italic. Incompatibility is not visible in [Publikator](https://github.com/orbiting/publikator-frontend).

Error seen else in comments.

Opened this issue albeit it is the Publikator's concern to not allow invalid formatting combinations. Having this in mind, MDAST/Markdown contents may be generated from other sources too e.g. comments and frontend should handle its inability in a graceful, even non-obstructive manner.

**Steps to Reproduce**

In staging environment:

1. Create an article in [Publikator](https://publikator.republik.love/) with a phrase in bold and a term in that phrase in italic, then publish said article.
2. Open published article.

**Actual Results**

Boldened, italicized term in boldened phrase is prefixed with message "Missing Markdown node type 'emphasis'". 

**Expected Results**

Error message should not be visible and as user I don't even realise that there is some formatting error.

Or as @tpreusse previously suggested to underline erroneous parts in a subtle manner.

**Comment by tpreusse** [comment]
The related styleguide issues:
https://github.com/orbiting/styleguide/issues/207
https://github.com/orbiting/styleguide/issues/220

We could limit rendering a visible missing node if logged in as editor. Should we do that? But then not a subtle one like comments.

**Comment by patrickvenetz** [comment]
> We could limit rendering a visible missing node if logged in as editor.

Yes :+1:

Can it be indicated that error message is only visible to editors?

**Comment by tpreusse** [comment]
https://github.com/orbiting/republik-frontend/pull/318
