### ISSUE TITLE
Enhancement: Mailadresse beim Abo-Teilen hinzufügen

### ISSUE THREAD

**Issue by lwihler** [orbiting/republik-frontend#281]
## Enhancement Wunsch

**Problembeschreibung**
Das CareTeam erhält ab und zu fälschlicherweise eine E-Mail auf die verschickte [Einladungsmail](https://mandrillapp.com/activity?date_format=dd%2Fmm%2Fyy&q=Einladung&date_range=7&start_date=12%2F03%2F2019&stop_date=19%2F03%2F2019&tag=_all&sender=&search-select-q=&api_key=&__csrf_token=95c561b54b4a66db9fa80993fcb6d073f97e3a9c), wenn jemand das Abo mit jemandem geteilt hat.

(Montag: 1, Dienstag: 4), 5 falsche Mails von 104 verschickten Anfragen = 4,81% von fehlerhaften Mails.

**Mögliche Lösung**

1. Schritt: Teilende informieren
Unter Konto -> [Republik teilen](https://www.republik.ch/konto#teilen) einen Einzeiler hinzufügen:
Bisher:
>Einen weiteren Zugriff teilen
>Beschenkte erhalten eine Einladungs-E-Mail mit einem Gutscheincode und Link zur /abholen-Seite, auf dem der Gutscheincode eingelöst werden kann.

Neu (Vorschlag):

>Einen weiteren Zugriff teilen
>Beschenkte erhalten eine Einladungs-E-Mail mit Ihrem Namen und Ihrer Mailadresse, einem Gutscheincode und Link zur /abholen-Seite, auf dem der Gutscheincode eingelöst werden kann. 

2. Schritt: Einladungsmail verändern:

>Maxime Mustertypin (Mäxin@fakemail.com) hat die Republik mit Ihnen geteilt.
>Und eine Nachricht für Sie mitgegeben:
>           Vielleicht gefällt sie dir.... Herzlich grüsst Mäxpäx
>Für 14 Tage sind Sie Gast an Bord. Und können nun unser Magazin entdecken, es lesen, sehen, hören und mitdiskutieren.

Alternativ: 2. Schritt: Reply to 
Reply to verändern, sodass beim Antworten die Mailadresse des Teilers drin steht

**Comment by tpreusse** [comment]
Implemented and deploy April 2nd.
