### ISSUE TITLE
Enhancement: Toggle full screen video player with key

### ISSUE THREAD

**Issue by Emaro** [orbiting/republik-frontend#282]
It would be really nice if you could toggle the full screen video player with the `f` key.

That is generally a nice feature, but since the full screen controls are hidden when the video is playing, it would be even more handy.

**Comment by tpreusse** [comment]
Thanks for the suggestion. I've implemented it, will get merged and go out sometime this week.

**Comment by tpreusse** [comment]
Btw.: it's live since yesterday 17h 🎉
