### ISSUE TITLE
"unliking" without "disliking" 

### ISSUE THREAD

**Issue by duembgen** [orbiting/republik-frontend#284]
## Bug Report

When I click the "like" button of a comment (in this case the ^ sign), I cannot undo this action. The only thing I can do is to "dislike" the comment instead (the v sign). 

**Steps to Reproduce**

* Go to URL [https://www.republik.ch/dialog?t=article&id=89be5e4a-9204-4d9b-9189-feba8dc61c17](https://www.republik.ch/dialog?t=article&id=89be5e4a-9204-4d9b-9189-feba8dc61c17)
* Scroll down to comments section
* Click on the "like button". 

**Actual Results**

See image below: I have mistakenly clicked the "like button" because I thought it would expand the article. Now I cannot do anything other than leave it like this, or dislike the article. The like button is deactivated. 

![image](https://user-images.githubusercontent.com/12606074/55225927-0ea48f80-5214-11e9-838a-345364d73866.png)

**Expected Results**

I want to be able to undo a "like" action, without "disliking" the post. 

**Environment**

This behavior has been seen on both Desktop (Ubuntu 16, Firefox) and Smartphone (Android, Chrome) devices, and seems to be platform-independent.  

**Possible Solutions**

The like button should not be completely disabled, but in a different mode. So that if I click on it again, I will undo my "like" action.

**Comment by duembgen** [comment]
This is more an unexpected behavior than a bug. I let you pick the best label and title.

**Comment by tpreusse** [comment]
Thanks for reporting. We decided to tackle this in our next sprint.

@wereHamster: @patte will provide an undo/reset vote mutation within in the next days.

**Comment by tpreusse** [comment]
Backend PR: https://github.com/orbiting/backends/pull/259

**Comment by patte** [comment]
@wereHamster fyi: the PR has been merged. `unvoteComment` is ready for consumption.

**Comment by tpreusse** [comment]
Implemented with https://github.com/orbiting/republik-frontend/pull/309 and already live.

**Comment by duembgen** [comment]
Works great, thank you for fixing this!
