### ISSUE TITLE
External links on about page

### ISSUE THREAD

**Issue by merzbenjamin** [orbiting/republik-frontend#325]
The links on https://www.republik.ch/about that point to external remarks / articles about republik.ch should open in a new tab / target="_blank"

**Comment by tpreusse** [comment]
We avoid `target="_blank"` in most cases for following reasons:
https://css-tricks.com/use-target_blank/

The choice to open a new window or not should be up to the user:
https://www.republik.ch/2018/01/13/launch-debatte/diskussion?focus=8885da1e-eefc-4f4c-a470-b5cbcefa9181
