### ISSUE TITLE
Multiple search not listing complete results

### ISSUE THREAD

**Issue by evenmeier** [orbiting/republik-frontend#427]
**Steps to Reproduce**

* Go to search page https://www.republik.ch/suche
* Click on the last example 
  Kombinierte Suche: ( … )
  Daniel ( Binswanger | Ryser | Graf )
* https://www.republik.ch/suche?q=Daniel%20(%20Binswanger%20%7C%20Ryser%20%7C%C2%A0Graf%20)
* Click on "Profile"
* https://www.republik.ch/suche?q=Daniel%20(%20Binswanger%20%7C%20Ryser%20%7C%C2%A0Graf%20)&fkey=type&fvalue=User

**Actual Results**

* Daniel Graf
* Daniel Graf
* Daniel Ryser

**Expected Results**

* Daniel Binswanger
* Daniel Graf
* Daniel Graf
* Daniel Ryser

**Environment**

BB (Android), Opera (Windows 10), ...

**Possible Solutions**

**Comment by ovbm** [comment]
Seems to have been fixed.
<img width="725" alt="Screenshot 2021-05-06 at 09 56 20" src="https://user-images.githubusercontent.com/20746301/117262228-51a0aa80-ae51-11eb-8ec8-826d54501569.png">
