### ISSUE TITLE
Poller stops polling

### ISSUE THREAD

**Issue by pozylon** [orbiting/republik-frontend#46]
If you lose network connection to the server, the poller stops polling, therefore users can be stuck on the login page.

This could occur if the user is connected through a shaky LTE/3G connection or even maybe when the backend gets redeployed.

**Comment by tpreusse** [comment]
Have a look at: https://www.apollographql.com/docs/react/basics/queries.html#graphql-config-options-errorPolicy

But might not work as advertised yet:  https://github.com/apollographql/apollo-client/issues/2703

Tried to use it for the [user name field](https://github.com/orbiting/republik-frontend/blob/29962bec5ae043fe98d219f3bc418952d449a993/components/Profile/UsernameField.js#L122) which throws errors until it's valid but didn't work.

**Comment by tpreusse** [comment]
If it does not work: fall back to pure client with `withApollo` and a regular query with poll interval.

**Comment by pozylon** [comment]
https://www.apollographql.com/docs/react/basics/queries.html#graphql-config-options-notifyOnNetworkStatusChange
