### ISSUE TITLE
Follow author UX improvement

### ISSUE THREAD

**Issue by annatraussnig** [orbiting/republik-frontend#465]
## Bug Report

When following an author on https://www.republik.ch/benachrichtigungen/einstellungen, said author jumps to the top of the section, which leads to quite awkward interactions

**Steps to Reproduce**

Go to https://www.republik.ch/benachrichtigungen/einstellungen
<img width="916" alt="Screenshot 2020-08-28 at 15 31 01" src="https://user-images.githubusercontent.com/3907984/91566167-887a0480-e943-11ea-9550-71a330532cd9.png">
Pick an author
Check "Magazin"

**Actual Results**

Bam! the author jumps up (cumbersome if you also planned to click "Debatte")

**Possible Solutions**

Only move the checked authors to the top of the section after page reload.

**Comment by dgnaegi** [comment]
Hi @annatraussnig 

I am currently in quarantine and as a pastime I'm participating at [hacktoberfest](https://hacktoberfest.digitalocean.com/) and practising my react skills. I opened a PR with a possible solution to this issue:

https://github.com/orbiting/republik-frontend/pull/487

I would appreciate a short review. If it's a fitting solution please add the "hacktoberfest-accepted" label to the PR :)

Best wishes
Daniel

**Comment by annatraussnig** [comment]
Oh, sorry to hear about the quarantine @dgnaegi – I hope it's not driving you up the walls. Really great that you are helping out with the bug, though! Many thanks! I'll have a look later today then :)

**Comment by annatraussnig** [comment]
Might be tomorrow or Thursday :/
Running a little bit tight today but let's see...

**Comment by annatraussnig** [comment]
Issue solved :) Thank you so much for your work!
