### ISSUE TITLE
Reading Position vs Audio

### ISSUE THREAD

**Issue by ovbm** [orbiting/republik-frontend#472]
## Bug Report
There are inconsistencies with regards to reading time and audio play time. 
Example: 

Zündstoff: Listening Time of 1h 40min - shows reading time of 1min in article. Same with "Caroline H" 1h 49min -> 21min.
![Screenshot 2020-09-11 at 10 52 22](https://user-images.githubusercontent.com/20746301/92897043-2928f380-f41d-11ea-92d7-81aaef9615a0.jpg)
![Screenshot 2020-09-11 at 10 52 52](https://user-images.githubusercontent.com/20746301/92897071-30500180-f41d-11ea-888a-45b5222f7cdb.jpg)
![Screenshot 2020-09-11 at 10 52 30](https://user-images.githubusercontent.com/20746301/92897078-30e89800-f41d-11ea-97c4-8ac5325c982b.jpg)

Also related #321
Should there be an option for someone to mark an audio article as 

Q: is this a bug or a not-yet-implemented feature of reading time

**Comment by tpreusse** [comment]
re the concrete examples:
> Zündstoff: Listening Time of 1h 40min - shows reading time of 1min in article.
I suppressed this one now via backend env. We should probably add a meta data flag to suppress it for overview aka «Auftakt» articles like this. 

> Same with "Caroline H" 1h 49min -> 21min.
Here the 21 minutes is the duration of the audio file for the first episode (via `estimatedConsumptionMinutes`). The 1h 49m in the carrousel is for the whole duration of all episodes.

**Comment by ovbm** [comment]
@tpreusse anything we need / can do for this issue?

**Comment by tpreusse** [comment]
@patrickvenetz do you have a opinion on this? From my side we could just close this issue.
