### ISSUE TITLE
mini ActionBar invisible but clickable

### ISSUE THREAD

**Issue by patte** [orbiting/republik-frontend#537]
## Bug Report

The floating mini Action-Bar (bottom right) becomes invisible when scrolling but is still clickable. The invisible buttons *overlay* other controls (for example video controls), so instead of the visible button the one from the ActionBar handles the click event.

**Steps to Reproduce**

- Scroll to bottom to make the mini ActionBar visible
- Scroll so that the ActionBar fades out
- Click where the ActionBar would be

**Actual Results**

https://user-images.githubusercontent.com/3500621/106342681-2e8abb80-62a2-11eb-929d-436b5c5b5fd1.mp4

https://user-images.githubusercontent.com/3500621/106342713-511cd480-62a2-11eb-8015-d96027f42360.mp4

**Expected Results**

The ActionBar is not clickable when faded out.

**Environment**

- OS: iOS 14.4, Linux
- Browser: Safari, Firefox 84

**Comment by tpreusse** [comment]
Thanks for reporting. Fix is now rolled out 😊
