### ISSUE TITLE
Secondary navigation won't keep section in view

### ISSUE THREAD

**Issue by patrickvenetz** [orbiting/republik-frontend#560]
## Bug Report

Secondary navigation behaves unexpectedly when clicking onto a section link. It seems it won't keep a section in view.

It either
a) resets secondary navigation (see example clip)
b) won't scroll section selected into view

---

### a) resets secondary navigation

**Steps to Reproduce**

1. Open republik.ch on a mobile device, or Republik-App
2. Click onto "Format" (a section)

**Actual Results**

Secondary navigation seems to reset.

https://user-images.githubusercontent.com/331800/111614089-7ed0c500-87df-11eb-8d2a-44de2077c7d4.mp4

**Expected Results**

Secondary navigation keeps "Format" in view.

---

### b) won't scroll section selected into view

**Steps to Reproduce**

1. Open republik.ch on a mobile device, or Republik-App
2. Click onto "Meta"
3. Make sure "Meta" is in view in secondary nav
4. Scroll to "Format", such that "Meta" out of view, then click on it
5. Hit back button

**Actual Results**

Secondary navigation seems to stick and never slide "Meta" into view.

https://user-images.githubusercontent.com/331800/111615737-606bc900-87e1-11eb-9bf0-db23db6236cc.mp4

**Expected Results**

Secondary navigation slides "Meta" into view again.

---

**Environment**

- OS: Android
- Browser: Firefox, Chrome and Republik-App

**Comment by ovbm** [comment]
It seems to me that b) is the expected behaviour... I wouldn't want to see "meta" when navigating to "format". What am I missing?

**Comment by patrickvenetz** [comment]
In b), I did hit "back space" and I'd expect subnav to scroll back to "Meta"
