### ISSUE TITLE
Newsletter re-subscription does not work like expected

### ISSUE THREAD

**Issue by fuenkchen** [orbiting/republik-frontend#607]
When a user wants to re-subscribe to newsletters it seems like, she can choose the newsletters she wants by clicking the corresponding checkboxes:
<img width="890" alt="Screenshot 2021-07-12 at 17 17 54" src="https://user-images.githubusercontent.com/4837884/125320797-56e01100-e33c-11eb-9973-557b0eba4722.png">
Instead, after confirming the subscription, all newsletters are again selected which were active before the user unsubscribed. 

So basically subscription and specific newsletter interests are two kind of things and we should make that clear to the user as well. 

We already have the info box shown above, which we could use with a slightly different text and add a link to subscribe (triggering about the same as it triggers now, when a user clicks on one of the checkboxes). For the checkboxes we could possibly:

a) Disable and gray them out, so that the user already sees, which newsletters will be activated after re-subscription
<img width="869" alt="Screenshot 2021-07-12 at 19 14 07" src="https://user-images.githubusercontent.com/4837884/125329142-6f085e00-e345-11eb-85d5-2b285204cc01.png">

b) Just remove the them 
<img width="860" alt="Screenshot 2021-07-12 at 19 14 32" src="https://user-images.githubusercontent.com/4837884/125329196-7c254d00-e345-11eb-84b9-aec05f67042f.png">

**Comment by tpreusse** [comment]
Yes, let's fix that!

I think this would require a new mutation to just update the newsletter status as described here:
https://github.com/orbiting/republik-admin-frontend/issues/40#issuecomment-469194467

Re A or B:
I'd suggest C – leave the checkboxes editable with the actual interest status selected as is and add a big button inside the green note to reactivate the newsletters which triggers the new mutation.

**Comment by fuenkchen** [comment]
Agree that it would be better to have a new mutation just for newsletter status changes.

About option C I'm not so sure, isn't it kind of misleading then when I can change interests but the changes will not have any effect because I'm unsubscribed?

(and also noted, that when we apply changes to /konto, we have to do it in admin tool as well)

**Comment by tpreusse** [comment]
I think the UI just has to be very clear for C to work. But I imagine the following use case:
> I do not receive the newsletters I desire because I unsubscribed from all by accident when I was annoyed at the daily newsletter. Now I go to my account and want to reactivate the newsletters but change my preference from daily & weekly to just weekly.

Now as far as I know to reactivate the newsletter status I have to confirm a email by mailchimp. So if I can't mutate my preference while the reactivation is pending I'll first have to go to my emails and then come back to my account and reload the page to actually change my interest. Similarly I'd imagine a customer support agent might want to change everything according to the wish of the customer without waiting for the confirmation.

Or would it be possible to skip the mailchimp confirmation mail with a dedicated mutation?

Also there is the case where I might not be eligible to receive certain newsletters:
<img width="852" alt="Screenshot 2021-07-14 at 14 22 34" src="https://user-images.githubusercontent.com/410211/125621307-d48bc172-8d28-4130-9f45-43e1f9e0b754.png">
Currently the checkboxes also stay mutable – I might want to adapt the preferences and then precede to buy a membership again.

**Comment by fuenkchen** [comment]
Right, that wouldn't be good UI too, with all the jumps between my account and my emails (not to forget community support). 
Not quite sure if we could skip mailchimp confirmation, but we shouldn't, opt-in mechanism is good in this case.

So C) it is with a very keen eye on a clear UI. (But anyways, first step: backend changes)

**Comment by ovbm** [comment]
@fuenkchen has this been fixed?

**Comment by fuenkchen** [comment]
Yes, fixed by https://github.com/orbiting/republik-frontend/pull/610 & https://github.com/orbiting/backends/pull/628
