### ISSUE TITLE
ActionBar not working in safari minimal ui (deadzone)

### ISSUE THREAD

**Issue by patte** [orbiting/republik-frontend#608]
## Bug Report

Trying any action in an article’s bottom ActionBar when in safari’s minimal ui toggles  safari to switch to the expanded layout instead of firing the action.

![D4F3C30B-1B0D-4A45-815B-5F7880F6309B](https://user-images.githubusercontent.com/3500621/125519402-6ee4e3dc-bfe0-4138-87fc-11d41cbd9637.jpeg)
👆buttons not working, instead changes to 👇

![8752B3DF-960E-4818-8CED-B753F6A78600](https://user-images.githubusercontent.com/3500621/125519415-cd36b6b8-0d68-4033-894f-c8b59279ea5f.jpeg)
In the expanded mode, the ActionBar works perfectly.

**Steps to Reproduce**

https://user-images.githubusercontent.com/3500621/125520095-c1ed0cb1-30fe-4e0f-8386-ee0cd892f685.MP4

**Environment**

- OS: iOS 14
- Browser: Safari

**Possible Solutions**

Don’t use a browser that changes it’s viewport all the time? 🤷

**Comment by tpreusse** [comment]
Thanks for the report @patte 🙇 

I prepared a fix which will deploy soonish, there is some css env magic to handle the iOS bottom nodge. And [apparently iOS 15](https://samuelkraft.com/blog/safari-15-bottom-tab-bars-web) will allow tabs in the deadzone again.
