### ISSUE TITLE
Bug: Notification page throws fatal error

### ISSUE THREAD

**Issue by patrickvenetz** [orbiting/republik-frontend#666]
## Bug Report

On notification page, an error is thrown when I click «more» on [notifications](https://www.republik.ch/benachrichtigungen) linked to a format.

<img width="724" alt="Bildschirmfoto 2021-10-31 um 14 13 56" src="https://user-images.githubusercontent.com/331800/139585266-bec4f8a3-e23c-4f8e-ad54-49ebc54c91ef.png">

**Comment by tpreusse** [comment]
Fix in https://github.com/orbiting/republik-frontend/commit/2f5a5cb7e993a538c07b95aab944326787efddb7 

Thx for the report 🙇
