### ISSUE TITLE
Regression: Follow-button missing on format pages

### ISSUE THREAD

**Issue by patrickvenetz** [orbiting/republik-frontend#667]
## Bug Report

Recently, follow-button in action bar on format pages vanished.

A format page (testing) now:

<img width="353" alt="Bildschirmfoto 2021-10-29 um 17 54 56" src="https://user-images.githubusercontent.com/331800/139585351-7e49c54d-b47d-476c-a668-0ebef3f603f3.png">

A format page before:

<img width="465" alt="Bildschirmfoto 2021-10-29 um 17 54 04" src="https://user-images.githubusercontent.com/331800/139585417-ae37bf8a-e914-4be6-ae76-53ecd5a0aa7c.png">

**Comment by tpreusse** [comment]
Fixed in https://github.com/orbiting/republik-frontend/commit/6cc0b09ce690d1bfc76b97c319c9127de1f804b5. Thx
