### ISSUE TITLE
Profile page: Dark-mode portrait placeholder too bright

### ISSUE THREAD

**Issue by patrickvenetz** [orbiting/republik-frontend#679]
Portrait image placeholder in contrast to background too bright in dark-mode.

In bright-mode:

<img width="503" alt="Bildschirmfoto 2021-11-11 um 11 35 37" src="https://user-images.githubusercontent.com/331800/141283783-a3e25609-662c-483c-b9f2-c6c6a0418c31.png">

In dark-mode:

<img width="496" alt="Bildschirmfoto 2021-11-11 um 11 35 47" src="https://user-images.githubusercontent.com/331800/141283966-a82acc05-86b5-4807-8b70-1daf7b4ece06.png">

**Comment by ovbm** [comment]
https://github.com/republik/plattform/pull/18
