### ISSUE TITLE
Merci.js, copy update

### ISSUE THREAD

**Issue by ovbm** [orbiting/republik-frontend#686]
Deliverables (Arjuna):
- [x] Copy

(Not corrected)
https://docs.google.com/document/d/1v24gadCvSiy2SMLMddAtgPHE7kEMu2CrPWOp3rMogsU/edit

**Comment by tpreusse** [comment]
Text in Google Doc looks good. Comment re one content thing.

Translation Keys:
- merci/title/package/PROLONG
- merci/title/package/PROLONG/noName
- merci/lead/package/PROLONG
- merci/action/read
- merci/action/profile

Currently we have create `Gesicht zeigen` button that leads to the profile if `!me.hasPublicProfile`. Should that one go away? Or maybe switch it to `!me.isListed` (available for `/community` with statement & picture). `Am Dialog teilnehmen` can be added as an additional action.
