### ISSUE TITLE
ProlongBox.js copy update

### ISSUE THREAD

**Issue by tpreusse** [orbiting/republik-frontend#687]
We have two main states of the prolong box. Before the expiration date: time - 30 days (T-30) to T0 and after the expiration T0 to T+14 (overdue, Periode we wait before switching off). 

## Before (T-30 bis T0)

Translation key space: `prolongNecessary/before`.

Same for everyone independent of subscription type.

> ### Der Republik treu bleiben: [Jetzt verlängern](/angebote?package=PROLONG)

Criteria: single line of text that does not annoy too much. Currently 43 chars.

## Overdue (T0 bis T+14)

Translation key space: `prolongNecessary/overdue`.

Default case:

> ### Ihr Mitglied­schafts­beitrag ist überfällig.
> #### Jetzt bezahlen (button)
> Ihre Mitgliedschaft wird am {graceEndDate} deaktiviert, wenn Sie bis dahin nicht bezahlen. Wollen Sie die Republik nicht mehr lesen? Bitte kündigen Sie Ihre Mitgliedschaft: [Teilen Sie uns mit, warum](/abgang).

This also has a special case for monthly gift subscription:

> ### Ihr Abonnement ist überfällig.
> #### Jetzt verlängern (button)
> Ihr Abonnement lief ( heute | gestern | vor X Tagen ) aus und wird am {graceEndDate} deaktiviert. Sie möchten uns nicht mehr lesen? [Sagen Sie uns, warum](/abgang).

**Comment by ovbm** [comment]
Von Arjuna:

> Von mir aus kann der zweite State (T0 bis T+14) so bleiben wie er ist.
> Den ersten State (T-30 bis T0) würde ich gerne anpassen auf:
> «Ihre Verlängerung steht an: Jetzt bezahlen (prolong Link)»
> 2 Dinge dazu (Falls es Fragen dazu gäbe oder so)
> Die Formulierung: «Ihre Verlängerung steht an» soll, zumindest in der Zwischenphase bis es eine richtige Lösung gibt, etwas Klarheit schaffen beim Drama bezüglich “die Mitgliedschaft verlängert sich automatisch aber eigentlich auch nicht und du musst händisch verlängern aber hier ist deine Rechnung warum hast du nicht gekündigt”
> Ja, es ist ein ungewohnt agressiver/fordernder Ton von der Republik. Ursprünglich war die Version milder mit dem Hintergedanken, dass ein agressiverer Störer den ersetzt bei T-2 bis T0. Wenn da aber nur ein Störer ist, muss es ein klarer call to action sein.
>  «jetzt bezahlen» soll bewirken, dass die erneuerungs/kündigungsquote höher ist, respektive weniger Mitgliedschaften einfach auslaufen (sobald es um Geld geht, checkt mensch, dass es eine Kündigung braucht – oder halt eine Zahlung).
