### ISSUE TITLE
Support Umlaut Domains in Profile

### ISSUE THREAD

**Issue by tpreusse** [orbiting/republik-frontend#94]
E.g.: öpfel.ch

Currently `valid-url` is used:
https://github.com/orbiting/republik-frontend/blob/ba0d1d6cb3f9126a577fff7a0f78e7e8f4f55048/components/Profile/Contact.js#L5

Switch to a url function from `validator`? Was used to fix the same issue with emails.

**Comment by maracuja-juice** [comment]
Hello Thomas
I would love to try solving some small issues in the republik repos and this seems like a good starting point.
I setup the backend and frontends like described in the docs and was able to login in with a test account. Also I added a Mailchimp API key to my environment.
For testing this issue I need local access to my profile page but when visiting that page I get the error: "index_not_found_exception".
What do I need to setup to be able to correctly access this page? I wasn't able to find something about in the docs.

It would be great if the steps to get a fully working frontend running will be added to the "How to Run" documentation in the future.

**Comment by tpreusse** [comment]
Hello @maracuja-juice

Awesome. Thank you for your interest in contributing and sorry about the setup issues.

We've just recently simplified our architecture and need to update our docs soon.

The `index_not_found_exception` comes from the backends, make sure to use the latest backend code from this week and then run `yarn run pull:elasticsearch` in the backends root directory to resolve it and initialise the elastic search indexes.

I just added it to the [backends readme](https://github.com/orbiting/backends/commit/f29b40268ef473fcf80e9950995fd381cc627fe7).

Alternatively you may [proxy our production backend](https://github.com/orbiting/republik-frontend#proxy-production-backend) to your local machine test some stuff with real content:
```
npm run yaproxy
```

Kind regards Thomas

**Comment by maracuja-juice** [comment]
Thank you Thomas for the answer and the documentation update. I will give it another go next weekend!

**Comment by maracuja-juice** [comment]
Hi Thomas.
I pulled the newest code and tried to run the command `yarn run pull:elasticsearch`.
Unfortunately it returned the exit code 1 with the following error:

```
ResponseError: invalid_alias_name_exception
    at IncomingMessage.<anonymous> (/home/mau/Documents/Dev/Republik/backends/node_modules/@elastic/elasticsearch/lib/Transport.js:296:25)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  meta: {
    body: { error: [Object], status: 400 },
    statusCode: 400,
    headers: {
      'content-type': 'application/json; charset=UTF-8',
      'content-length': '455'
    },
    warnings: null,
    meta: {
      context: null,
      request: [Object],
      name: 'elasticsearch-js',
      connection: [Object],
      attempts: 0,
      aborted: false
    }
  }
}
error Command failed with exit code 1.
```

<details><summary>full execution log</summary>

<p>

```
yarn run v1.22.5
$ GITHUB_GRAPHQL_RATELIMIT=true node packages/search/script/pullElasticsearch.js
missing env FIREBASE_*, sending push notifications via firebase will not work
missing env APN_*, sending push notifications via apn will not work
missing TWITTER_APP_KEY. Twitter Embeds won't work.
missing TWITTER_APP_SECRET. Twitter Embeds won't work.
missing YOUTUBE_APP_KEY. Youtube Embeds won't work.
missing VIMEO_APP_ACCESS_TOKEN. Vimeo embeds won't work.
missing env AWS_ACCESS_KEY_ID and/or AWS_SECRET_ACCESS_KEY, uploading images will not work
missing env AWS_S3_BUCKET, uploading new and deleting existing images will not work
missing env PDF_BASE_URL, the /pdf endpoint will not work
missing env KEYCDN_*, purgeUrls and purgeTags will not work
missing CHROMIUM_LAMBDA_URL, the /render endpoint will not work
missing env AWS_BUCKET_ALLOWLIST, the /:bucket/:path* endpoint will not work
Posting to slack disabled: missing SLACK_API_TOKEN
remove write alias {
  writeAlias: 'republik-comment-write',
  index: 'republik-comment-2021-03-20-15-00-57'
}
remove write alias {
  writeAlias: 'republik-document-write',
  index: 'republik-document-2021-03-20-15-00-57'
}
remove write alias {
  writeAlias: 'republik-user-write',
  index: 'republik-user-2021-03-20-15-00-57'
}
remove write alias {
  writeAlias: 'republik-repo-write',
  index: 'republik-repo-2021-03-20-15-00-57'
}
creating index {
  writeAlias: 'republik-user-write',
  index: 'republik-user-2021-03-20-15-00-57'
}
creating index {
  writeAlias: 'republik-document-write',
  index: 'republik-document-2021-03-20-15-00-57'
}
creating index {
  writeAlias: 'republik-repo-write',
  index: 'republik-repo-2021-03-20-15-00-57'
}
creating index {
  writeAlias: 'republik-comment-write',
  index: 'republik-comment-2021-03-20-15-00-57'
}
ResponseError: invalid_alias_name_exception
    at IncomingMessage.<anonymous> (/home/mau/Documents/Dev/Republik/backends/node_modules/@elastic/elasticsearch/lib/Transport.js:296:25)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  meta: {
    body: { error: [Object], status: 400 },
    statusCode: 400,
    headers: {
      'content-type': 'application/json; charset=UTF-8',
      'content-length': '455'
    },
    warnings: null,
    meta: {
      context: null,
      request: [Object],
      name: 'elasticsearch-js',
      connection: [Object],
      attempts: 0,
      aborted: false
    }
  }
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</p>
</details>

PS: Maybe we should create a new issue for these setup problems, sorry that I hijacked this issue :smiley:

**Comment by tpreusse** [comment]
Fixed and finally released. Thx @panmau.

Re the backend setup issue: maybe you have the wrong elasticsearch version running? The backend currently needs v6. Feel free to open a new setup issue in backend repo if it's still an issue.

**Comment by patrickvenetz** [comment]
Regarding setup issue: This usually occures when data is posted to ElasticSearch before mapping, indices and aliases are setup. Also, detailed error message burried in `meta.body.error` and thus gosh darn unreadable.

Since we ran into before, I shall improve error logging and add some routine to delete a corrupted index.
